title: Priyanka Birajdar # your name (or website title) here
logo: "/Priyanka.JPG?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
 Senior Software Engineer I
  <br><br>
  <a href="mailto: piabirajdar@gmail.com">piabirajdar@gmail.com </a>
  <br>
  <a href="https://www.linkedin.com/in/priyankabirajdar/">LinkedIn Profile</a>
  <br>
  <a href="https://github.com/piabirajdar/">Github</a> 
theme: jekyll-theme-dinky
